// <auto-generated />
using Manifest.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Manifest.Persistence.Migrations
{
    [DbContext(typeof(ManifestDbContext))]
    [Migration("20190715002123_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Manifest.Domain.Entities.Aircraft", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<int>("Capacity");

                    b.HasKey("Name");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("Manifest.Domain.Entities.Person", b =>
                {
                    b.Property<string>("ManifestNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<bool>("IsAffInstructor");

                    b.Property<bool>("IsCoach");

                    b.Property<bool>("IsTandemInstructor");

                    b.Property<bool>("IsVideographer");

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.HasKey("ManifestNumber");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
